<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            div.scroll {
                width: 500px;
                height: 250px;
                overflow: scroll;
                margin: auto;
                border: 3px solid #73AD21;
                padding: 10px;
            }
        </style>
    </head>
    <body>
        <h1>Imprimindo números</h1>

        <?php if (isset($numbers)) : ?>
            <h2>Hello!</h2>
            <div class="scroll">
                <?php
                    foreach ($numbers as $number) {
                        echo $number . '&nbsp;&nbsp;&nbsp;';
                    }
                    echo '</br></br>Quantidade de Multiplo de 3: ' . $multipleOf3;
                    echo '</br>Quantidade de Multiplo de 5: ' . $multipleOf5;
                    echo '</br>Quantidade de Multiplo de 3 e 5: ' . $multipleOf3And5;
                    echo '</br>Quantidade de Sem Multiplo de 3 e 5: ' . $notMultiple;
                    echo '</br></br> Total Impresso: '. ($multipleOf3+$multipleOf5+$multipleOf3And5+$notMultiple)
                ?>
            </div>
        <?php else: ?>
            <p>Não tem números para serem impressos</a></p>
        <?php endif; ?>
    </body>
</html>
